apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}
    {{- if .Values.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}        
{{ toYaml .Values.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "fullname" . }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: mntdockercontainers
              mountPath: /mnt/docker/containers
              readOnly: true
            - name: fluentconfig
              mountPath: {{ .Values.fluentdConfigPath }}
          env:
            - name: FLUENT_PAPERTRAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname-secrets" . }}"
                  key: papertrail-host
            - name: FLUENT_PAPERTRAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname-secrets" . }}"
                  key: papertrail-port
            - name: FLUENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: FLUENTD_OPT
              value: "{{ .Values.fluentdOpt }}"
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: mntdockercontainers
          hostPath:
            path: /mnt/docker/containers
        - name: fluentconfig
          configMap:
            name: "{{ template "fullname-configmaps" . }}"
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
  updateStrategy:
    type: "{{ .Values.updateStrategy }}"
