apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "fullname-secrets" . }}"
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
data:
  papertrail-port: {{ default "MISSING" .Values.papertrail.port | b64enc | quote }}
  papertrail-host: {{ default "MISSING" .Values.papertrail.host | b64enc | quote }}
