apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "resultsviewer-backend.fullname" . }}
  labels:
    app: {{ template "resultsviewer-backend.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "resultsviewer-backend.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.prometheus.enabled }}
        prometheus.io/scrape: {{ .Values.prometheus.scrape | quote }}
        prometheus.io/probe: {{ .Values.prometheus.probe | quote }}
        prometheus.io/path: {{ .Values.prometheus.path | quote }}
        prometheus.io/port: {{ .Values.prometheus.port | quote }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- if .Values.vault.enabled }}
      initContainers:
      {{- include "vault_init_container" . | indent 8 }}
      {{- end }}
        # create trust store with Consul CA + default CA trust store to use for java run time
        - name: bossanova-ca-to-truststore
          image: {{ .Values.bossanovaTrustStoreConfiguration.image }}
          imagePullPolicy: {{ .Values.bossanovaTrustStoreConfiguration.pullPolicy }}
          env:
            - name: TRUSTSTORE_JKS
              value: "{{ .Values.bossanovaTrustStoreConfiguration.truststorePath }}/{{ .Values.bossanovaTrustStoreConfiguration.trustStoreName }}"
            - name: TRUSTSTORE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "resultsviewer-backend.fullname" . }}
                  key: truststoreSecret
            - name: CONSUL_CA_BUNDLE
              value: {{ (printf "%v/%v" .Values.consul.caMountPath .Values.consul.caBundleFilename) | quote }}
          command:
            - '/bin/bash'
          args:
            - '-c'
            - 'apk add --no-cache openssl coreutils && keytool -v -import -noprompt -file $CONSUL_CA_BUNDLE -keystore $TRUSTSTORE_JKS -storepass $TRUSTSTORE_SECRET -alias bossanova-ca-bundle && keytool -importkeystore -srckeystore /opt/jdk/jre/lib/security/cacerts -destkeystore $TRUSTSTORE_JKS -srcstorepass changeit -deststorepass $TRUSTSTORE_SECRET'
          volumeMounts:
            - mountPath: {{ .Values.bossanovaTrustStoreConfiguration.truststorePath }}
              name: {{ .Values.bossanovaTrustStoreConfiguration.trustStoreMountName }}
            - mountPath: {{ .Values.consul.caMountPath }}
              name: {{ .Values.consul.caSecretName }}
              readOnly: true
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "resultsviewer-backend.image-url" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.vault.enabled }}
          {{- include "vault_token_env_var" . | indent 10 }}
          {{- end }}
          {{- if .Values.vault.auth.requestsCaBundle }}
          - name: REQUESTS_CA_BUNDLE
            value: {{ .Values.vault.auth.requestsCaBundle }}
          {{- end }}
          {{- if .Values.consul.enabled }}
          - name: CONSUL_HTTP_ADDR
            value: {{ .Values.consul.addr}}
          {{- end }}
          {{- if .Values.vault.enabled }}
          - name: VAULT_ADDR
            value: {{ .Values.vault.addr}}
          {{- end }}
          - name: LOGGING_LEVEL
            value: {{ .Values.logging.logLevel }}
          - name: TRUSTSTORE_JKS
            value: "{{ .Values.bossanovaTrustStoreConfiguration.truststorePath }}/{{ .Values.bossanovaTrustStoreConfiguration.trustStoreName }}"
          - name: TRUSTSTORE_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "resultsviewer-backend.fullname" . }}
                key: truststoreSecret
          - name: JAVA_OPTIONS
            value: -DLOGGING_LEVEL=$(LOGGING_LEVEL) -Djavax.net.ssl.trustStore=$(TRUSTSTORE_JKS) -Djavax.net.ssl.trustStorePassword=$(TRUSTSTORE_SECRET) -Djava.net.preferIPv4Stack=true
          - name: ENVCONSUL_CONFIG
            value: "{{ .Values.configMountPath }}/{{ .Values.envconsul.configFileName }}"
          {{- if .Values.prometheus.enabled }}
          - name: PROMETHEUS_PORT
            value: {{ .Values.prometheus.port | quote }}
          {{- end }}
          ports:
            {{- if .Values.prometheus.enabled }}
            - containerPort: {{ .Values.prometheus.port }}
              name: metrics
              protocol: TCP
            {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.configMountPath }}
              name: {{ template "resultsviewer-backend.fullname" . }}
            - mountPath: {{ .Values.bossanovaTrustStoreConfiguration.truststorePath }}
              name: {{ .Values.bossanovaTrustStoreConfiguration.trustStoreMountName }}
            {{- if .Values.vault.caSecretName }}
            - mountPath: {{ .Values.vault.caMountPath }}
              name: {{ .Values.vault.caSecretName }}
              readOnly: true
            {{- end }}
            {{- if .Values.consul.caSecretName }}
            - mountPath: {{ .Values.consul.caMountPath }}
              name: {{ .Values.consul.caSecretName }}
              readOnly: true
            {{- end }}
          # Since liveness currently depends on Prometheus
          {{- if .Values.prometheus.enabled }}        
          livenessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.prometheus.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
        - name: {{ template "resultsviewer-backend.fullname" . }}
          configMap:
            name: {{ template "resultsviewer-backend.fullname" . }}
        - name: {{ .Values.bossanovaTrustStoreConfiguration.trustStoreMountName }}
          emptyDir: {}
        {{- if .Values.vault.caSecretName }}
        - name: {{ .Values.vault.caSecretName }}
          secret:
            secretName: {{ .Values.vault.caSecretName }}
        {{- end }}
        {{- if .Values.consul.caSecretName }}
        - name: {{ .Values.consul.caSecretName }}
          secret:
            secretName: {{ .Values.consul.caSecretName }}
        {{- end }}
