apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "sas-token.fullname" . }}
  labels:
    app: {{ template "sas-token.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  minAvailable: {{ .Values.minAvailable }}
  selector:
    matchLabels:
      app: {{ template "sas-token.name" . }}
