apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sas-token.fullname" . }}
  labels:
    app: {{ template "sas-token.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ .Values.keystores.passwordSecret.key }}: "{{ randAlphaNum 24 | b64enc }}"
