{{- if .Values.cantaloupeProperties.custom -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}
data:
  {{ .Values.cantaloupeProperties.templateName }}: !unsafe |-
{{ .Values.cantaloupeProperties.value | indent 4 }}
{{- end -}}
