replicaCount: 1
minAvailable: 1
image:
  repository: bossanova-cloud-container.jfrog.io/cloud-apps/
  name: resultsviewer-backend-service
  tag: 0.0.25
  pullPolicy: Always
imagePullSecrets:
  - dpr-secret
serviceAccountName: resultsviewer-backend-service
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
envconsul:
  configFileName: envconsul-config.hcl
  pristine: true
  sanitize: true
  upcase: true
  secrets: []
  prefixes: []

vault:
  enabled: True
  addr: http://10.0.2.2:8200
  auth:
    role: resultsviewer-backend-service
    debug: true

consul:
  enabled: True
  addr: http://10.0.2.2:8500  

papertrailRegistration:
  apiToken: ""
  host: ""
  port: ""

postgresMigrationCommand:
  - "envconsul"
  - "-config=$(ENVCONSUL_CONFIG)"
postgresMigrationCommandArgs:
  - "/opt/flyway.sh"
  - "migrate"

prometheus:
  enabled: true
  scrape: true
  probe: true
  port: 9397
  path: /metrics

livenessProbe:
  port: 9397
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

logging:
  logLevel: INFO
  configFileName: logging.properties
  conversionPattern: "%-5p [%t]: %m%n"

configMountPath: /etc/config
