{{- template "common.configmap" (list . "oos-delivery.configmap") -}}
{{- define "oos-delivery.configmap" -}}
data:
  {{ .Values.envconsul.configFileName }}: |-
    pristine = {{ .Values.envconsul.pristine }}
    sanitize = {{ .Values.envconsul.sanitize }}
    upcase = {{ .Values.envconsul.upcase }}
    {{- range $index, $secret := .Values.envconsul.secrets }}
    secret {
      path = {{ $secret.path | quote }}
      no_prefix = {{ default "true" $secret.noPrefix }}
      format = {{ default "{{ key }}" $secret.format | quote }}
    }
    {{- end }}
    {{- range $index, $prefix := .Values.envconsul.prefixes }}
    prefix {
      path = {{ $prefix.path | quote }}
    }
    {{- end }}
    consul {
      ssl {
        {{- if .Values.consul.caSecretName }}
        ca_cert = {{ (printf "%v/%v" .Values.consul.caMountPath .Values.consul.caBundleFilename) | quote }}
        {{- end }}
      }
    }
    vault {
      ssl {
        {{- if .Values.vault.caSecretName }}
        ca_cert = {{ (printf "%v/%v" .Values.vault.caMountPath .Values.vault.caBundleFilename) | quote }}
        {{- end }}
      }
    }
  {{ .Values.logging.configFileName }}: {{ .Values.logging.config | quote }}
  # [T2A-186] nkiraly_credential_shim: service bus credential mapping shim until [T2A-187] has oos-delivery use 1 environment variable set for indexer API topic subscription
  {{ .Values.environmentMapperFileName }}: |-
    export DATALAKE_REQUEST_SERVICEBUS_TOPIC_NAME=$DATALAKE_INDEXAPI_SERVICEBUS_TOPIC_NAME
    export DATALAKE_REQUEST_SERVICEBUS_SUBSCRIPTION_NAME=$DATALAKE_INDEXAPI_SERVICEBUS_SUBSCRIPTION_NAME
    export DATALAKE_REQUEST_SERVICEBUS_KEY_NAME=$DATALAKE_INDEXAPI_SERVICEBUS_KEY_NAME
    export DATALAKE_REQUEST_SERVICEBUS_KEY_VALUE=$DATALAKE_INDEXAPI_SERVICEBUS_KEY_VALUE
    export DATALAKE_REQUEST_SERVICEBUS_NAMESPACE=$DATALAKE_INDEXAPI_SERVICEBUS_NAMESPACE
    export DATALAKE_RESPONSE_SERVICEBUS_TOPIC_NAME=$DATALAKE_INDEXAPI_SERVICEBUS_TOPIC_NAME
    export DATALAKE_RESPONSE_SERVICEBUS_SUBSCRIPTION_NAME=$DATALAKE_INDEXAPI_SERVICEBUS_SUBSCRIPTION_NAME
    export DATALAKE_RESPONSE_SERVICEBUS_KEY_NAME=$DATALAKE_INDEXAPI_SERVICEBUS_KEY_NAME
    export DATALAKE_RESPONSE_SERVICEBUS_KEY_VALUE=$DATALAKE_INDEXAPI_SERVICEBUS_KEY_VALUE
    export DATALAKE_RESPONSE_SERVICEBUS_NAMESPACE=$DATALAKE_INDEXAPI_SERVICEBUS_NAMESPACE
    oos_delivery
{{- end }}
