{{- template "common.configmap" (list . "oos-delivery.configmap") -}}
{{- define "oos-delivery.configmap" -}}
data:
  {{ .Values.envconsul.configFileName }}: |-
    pristine = {{ .Values.envconsul.pristine }}
    sanitize = {{ .Values.envconsul.sanitize }}
    upcase = {{ .Values.envconsul.upcase }}
    {{- range $index, $secret := .Values.envconsul.secrets }}
    secret {
      path = {{ $secret.path | quote }}
      no_prefix = {{ default "true" $secret.noPrefix }}
      format = {{ default "{{ key }}" $secret.format | quote }}
    }
    {{- end }}
    {{- range $index, $prefix := .Values.envconsul.prefixes }}
    prefix {
      path = {{ $prefix.path | quote }}
    }
    {{- end }}
    consul {
      ssl {
        {{- if .Values.consul.caSecretName }}
        ca_cert = {{ (printf "%v/%v" .Values.consul.caMountPath .Values.consul.caBundleFilename) | quote }}
        {{- end }}
      }
    }
    vault {
      ssl {
        {{- if .Values.vault.caSecretName }}
        ca_cert = {{ (printf "%v/%v" .Values.vault.caMountPath .Values.vault.caBundleFilename) | quote }}
        {{- end }}
      }
    }
  {{ .Values.logging.configFileName }}: {{ .Values.logging.config | quote }}
  # [T2A-177] nkiraly_pgsql_shim: postgresql authn shim until [T2A-128] oos-delivery honors MASTER and READ connection credential leases
  {{ .Values.pgsqlCredentialWrapperFileName }}: |-
    export PGSQL_USER=$PGSQL_WRITE_USERNAME
    export PGSQL_PASSWORD=$PGSQL_WRITE_PASSWORD
    oos_delivery
{{- end }}
