apiVersion: v1
kind: Secret
metadata:
  name: {{ template "oos-delivery.name" . }}-env
  labels:
    app: "{{ template "oos-delivery.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-11"
type: Opaque
data:
  {{- range $varKey, $varVal := .Values.environmentSecrets }}
  {{ $varKey }}: {{ $varVal | b64enc | quote }}
  {{- end }}
