apiVersion: policy/v1beta1
kind: PodDisruptionBudget
{{ template "common.metadata" . }}
spec:
  minAvailable: {{ .Values.minAvailable }}
  selector:
    matchLabels:
      app: {{ template "oos-detection.name" . }}
      release: {{ .Release.Name }}
