apiVersion: v1
description: Chart partial to do application database migration using Helm hooks
name: postgres-migration-job
version: 0.0.3
maintainers:
  - name: Nicholas Kiraly (@nkiraly)
    email: nicholas.kiraly@bossanova.com
