{{- template "common.configmap" (list . "walmart-integration.configmap") -}}
{{- define "walmart-integration.configmap" -}}
data:
  {{ .Values.envconsul.configFileName }}: |-
    pristine = {{ .Values.envconsul.pristine }}
    sanitize = {{ .Values.envconsul.sanitize }}
    upcase = {{ .Values.envconsul.upcase }}
    {{- range $index, $secret := .Values.envconsul.secrets }}
    secret {
      path = {{ $secret.path | quote }}
      no_prefix = {{ default "true" $secret.noPrefix }}
    }
    {{- end }}
    {{- range $index, $prefix :=.Values.envconsul.prefixes }}
    prefix {
      path = {{ $prefix.path | quote }}
    }
    {{- end }}
  {{ .Values.log4j.configFileName }}: |-
    log4j.rootLogger={{ .Values.log4j.logLevel }}, STDOUT
    log4j.appender.STDOUT=org.apache.log4j.ConsoleAppender
    log4j.appender.STDOUT.layout=org.apache.log4j.PatternLayout
    log4j.appender.STDOUT.layout.ConversionPattern={{ .Values.log4j.conversionPattern }}
{{- end }}
