apiVersion: v1
kind: Secret
metadata:
  name: {{ template "walmart-integration.fullname" . }}
  labels:
    app: {{ template "walmart-integration.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  truststoreSecret: "{{ randAlphaNum 24 | b64enc }}"
