apiVersion: v1
description: A Helm chart for deploying an authentication proxy in front of a Kubernetes service
name: auth-proxy
version: 0.0.1
appVersion: 0.0.1
maintainers:
  - name: Marc Sensenich (@marc-sensenich)
    email: marc.sensenich@bossanova.com

